name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch:

env:
  MANIFEST: https://github.com/PitchBlackTWRP/manifest_pb.git -b android-6.0
  DEVICE: S11
  DT_LINK: https://github.com/Abducoffee/s11
  DT_PATH: device/itel/S11
  TARGET: recoveryimage
  OUTPUT: recovery.img

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5
        sudo add-apt-repository universe
        sudo apt -y install libncurses5
            
       - uses: webfactory/ssh-agent@v0.5.4
         with:
              ssh-private-key: |
                    ${{ secrets.SSH_PRIVATE_KEY }}
            

       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
              sudo apt update && sudo apt install zip
              sudo apt update && sudo apt install zip
              zip -r rec.zip /home/runner/work/Recovery-Builder/Recovery-Builder/work/out/target/product/$DEVICE/$OUTPUT
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: my-artifact
            path: /home/runner/work/Recovery-Builder/Recovery-Builder/work/rec.zip
            retention-days: 5
